// Generated by CoffeeScript 1.6.2
(function() {
  describe('Hello World', function() {
    return it('says hello', function() {
      return expect(helloWorld()).toEqual('Hello world!');
    });
  });

}).call(this);
